### ISSUE TITLE
Generate and export named event responses for ethers v5

### ISSUE THREAD

**Issue by Siegrift** [dethcrypto/TypeChain#440] opened 2021-08-02 14:10 UTC
Currently TypeChain generates types similar to the following:

```ts
class ContractAbc extends Contract {
...
  filters: {
    TemplateCreated(
      templateId: BytesLike | null,
      airnodeId: null,
      endpointId: null,
      parameters: null
    ): TypedEventFilter<
      [string, string, string, string],
      {
        templateId: string;
        airnodeId: string;
        endpointId: string;
        parameters: string;
      }
    >;
    ...
```

The problem is that I can't use filters to query my event. Instead I want to pass `tx.hash`, and parse the logs myself. However at that point I would like to cast my event response to the Type generated by TypeChain.

For example, this code:
```ts
    contractAbc.provider.once(tx.hash, (tx) => {
      const parsedLog = airnodeRrp.interface.parseLog(tx.logs[0]);
      resolve(parsedLog.args.templateId); // This is untyped (args is basically any)
    })
```

Instead I would like to have a code like this:
```ts
    contractAbc.provider.once(tx.hash, (tx) => {
      const parsedLog = airnodeRrp.interface.parseLog(tx.logs[0]).args as TemplateCreatedEvent;
      resolve(parsedLog.templateId); // parsedLog should be typed
    })
```

Slightly related: https://github.com/ethereum-ts/TypeChain/issues/249

**Comment by StErMi** [comment] 2021-08-13 06:00
It would be cool to have the possibility to explicitly say in the typechain export moment which interface use for types so also those interfaces would be exported and be usable on the frontend side directly

**Comment by krzkaczor** [comment] 2021-09-12 20:42
Done in https://github.com/dethcrypto/TypeChain/releases/tag/%40typechain%2Fethers-v5%407.1.0

Duplicate of: https://github.com/dethcrypto/TypeChain/issues/398

**Closed by krzkaczor** 2021-09-12 20:42 UTC

**Comment by StErMi** [comment] 2021-09-13 05:42
damn cool!
