### ISSUE TITLE
out dir customization

### ISSUE THREAD

**Issue by LoganAtCrypto** [dethcrypto/TypeChain#632] opened 2022-03-03 01:12 UTC
Hi team, thanks for the awesome project.

My situation is that, I have lots of json ABI files, and those ABI files are located in lots of different folder/sub projects and the ABI file names may conflict with each other. I'd like to the type files generated by TypeChain located in the same directions as their corresponding source ABI json file. Does TypeChain support this kind of out dir customization?

What I want is something like the following

Source ABI files

```
packages/A/abis/hello.json
packages/A/abis/world.json

packages/B/abis/hello.json
packages/B/abis/myContract.json
```

After running TypeChain
```
packages/A/abis/hello.json
packages/A/abis/world.json
packages/A/abis/hello.generated.ts
packages/A/abis/world.generated.json

packages/B/abis/hello.json
packages/B/abis/myContract.json
packages/B/abis/hello.generated.json
packages/B/abis/myContract.generated.json
```

Thanks again!

**Comment by krzkaczor** [comment] 2022-03-03 09:27
Hey! Currently, TypeChain flattens paths of all files that it found. So in your example, you would end up with
`out/hello.json` silently overridden :( 

The good news is that we are working right *now* on fixing this (CC: @hasparus). 

As a temp workaround, you can run TypeChain multiple times, with different out dir ie. 

* `typechain --out-dir our/a/ packages/A/**/.json`
* `typechain --out-dir our/b/ packages/B/**/.json`

I am gonna close it as a duplicate of: https://github.com/dethcrypto/TypeChain/issues/545

**Closed by krzkaczor** 2022-03-03 09:27 UTC
