### ISSUE TITLE
Extract variable/parameter type

### ISSUE THREAD

**Issue by teddav** [dethcrypto/TypeChain#462] opened 2021-09-06 14:05 UTC
Maybe I missed it... but I think there is currently no way to get the type of a struct/a variable in a contract, or the parameter of a function. Would it be possible to extract those types and access them individually?
I am using a custom wrapper function around a getter for a struct and I usually type the return of the function manually with a generic.
Example:
I have a contract:
```solidity
contract Abc {
  struct MyStruct {
    uint256 structParam1;
    uint256 structParam2;
  }

  function doSmthg(uint256 amount, address user) {
    ...
  }
}
```

In my TS code I want to do something like this:
```js
import { Abc__factory } from './typechain';

const getStruct = <T>(contractAddress: string, interface: Interface, structName: string): T => {
  ...  
}

const interface = Abc__factory.createInterface()
const struct = getStruct<????>("0x000", interface, "MyStruct")
```

So I want to be able to call my `getStruct` function with the correct type, which means, getting the type of `MyStruct`.
And same for function parameters, I would like to be able to get the type of `amount` and `user`, of the `doSmthg` function.

Thanks

**Comment by GuillaumeNervoXS** [comment] 2021-09-07 10:39
I have been stucked on this for a week now too...

Up for an answer :)

**Comment by krzkaczor** [comment] 2021-09-12 20:30
Duplicate of: https://github.com/dethcrypto/TypeChain/issues/398

**Closed by krzkaczor** 2021-09-12 20:30 UTC
